version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: >
      sh -c "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True